# $FreeBSD$

PORTNAME=	goattracker2
PORTVERSION=	2.73.0
CATEGORIES=	audio

MAINTAINER=	olivia@foxiepa.ws
COMMENT=	Crossplatform music editor for creating Commodore 64 music

LICENSE=	GPLv2

LIB_DEPENDS=	libSDL.so:${PORTSDIR}/devel/sdl12

USES=		gmake

USE_GITHUB=	yes
GH_ACCOUNT=	foxiepaws
GH_PROJECT=	goattrk2
GH_COMMIT=	a57338f
GH_TAG=		2.73.0

.include <bsd.port.mk>
