# $FreeBSD$

PORTNAME=	goattracker2
PORTVERSION=	2.73.0
PORTREVISION=	0
CATEGORIES=	audio
MAINTAINER=	olivia@foxiepa.ws
COMMENT=	A crossplatform music editor for creating Commodore 64 music.
USES=		gmake
USE_GITHUB=	yes
GH_ACCOUNT=	foxiepaws
GH_PROJECT=	goattrk2
GH_COMMIT=	a57338f	
GH_TAG=		2.73.0
LIB_DEPENDS=	libSDL-1.2.so.0:${PORTSDIR}/devel/sdl12

.include <bsd.port.mk>
