# $FreeBSD$

PORTNAME=	goattracker2
PORTVERSION=	2.73
PORTREVISION=	0
CATEGORIES=	audio
MAINTAINER=	olivia@foxiepa.ws
COMMENT=	A crossplatform music editor for creating Commodore 64 music.
USES=		gmake
USE_GITHUB=yes
GH_ACCOUNT=foxiepaws
GH_PROJECT=goattrk2
GH_TAGNAME=${PORTVERSION}

# check this every once in a while to make sure it doesn't disappear.









.include <bsd.port.mk>
